### ISSUE TITLE
Создать Листок с задачами, теорией и версией для печати

### ISSUE THREAD

**Issue by gurovic** [school-letovo/economics#147]
- [ ] #262

- [ ] создать модель Paper - листок, состояший из последовательности задач и теории

- [ ] сделать страничку отображения листка учителю (по аналогии с TestSet)

- [ ] сделать страничку отображения листка ученика (по аналогии с TestSet)

- [ ] потестить, что происходит с картинками,  в том числе, решить issue с добавлением картинок не админом
